# Generated by Django 3.2.3 on 2021-09-30 09:25

from django.db import migrations, models
import django.db.models.deletion


def generate_questiontype(apps, schema_editor):
    INPUT_TYPES = (
        'bool',
        'choice',
        'date',
        'daterange',
        'extchoicenotlisted',
        'externalchoice',
        'externalmultichoiceonetext',
        'extmultichoicenotlistedonetext',
        'multichoiceonetext',
        'multidmptypedreasononetext',
        'multinamedurlonetext',
        'multirdacostonetext',
        'namedurl',
        'positiveinteger',
        'reason',
        'shortfreetext',
        'storageforecast'
    )
    QuestionType = apps.get_model('dmpt', 'QuestionType')
    objs = (QuestionType(id=input_type) for input_type in INPUT_TYPES)
    QuestionType.objects.bulk_create(objs, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0001_squashed_0011_section_optional_squashed_0008_switch_to_native_JSONField'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RunPython(generate_questiontype, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='question',
            name='dmpt_questi_input_t_d0047e_idx',
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['input_type', 'id'], name='dmpt_questi_input_t_490039_idx'),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmpt.questiontype'),
        ),
    ]
