# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='template',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set([('version', 'title')]),
        ),
    ]
