# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-25 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easydmp.dmpt.utils


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0001_squashed_0031_improve_cloning'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplicitBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Last', 'Last'), ('CannedAnswer', 'CannedAnswer'), ('ExplicitBranch', 'ExplicitBranch'), ('Edge', 'Edge'), ('Node-edgeless', 'Node-edgeless')], max_length=16)),
                ('condition', models.CharField(blank=True, max_length=255)),
                ('current_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_transitions', to='dmpt.Question')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backward_transitions', to='dmpt.Question')),
            ],
            bases=(easydmp.dmpt.utils.DeletionMixin, models.Model),
        ),
        migrations.AddField(
            model_name='cannedanswer',
            name='transition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmpt.ExplicitBranch', related_name='canned_answers'),
        ),
        migrations.AlterUniqueTogether(
            name='explicitbranch',
            unique_together=set([('current_question', 'category', 'condition', 'next_question')]),
        ),
    ]
