# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-24 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0002_add_ExplicitBranch_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('template', 'title'), ('template', 'super_section', 'position')]),
        ),
    ]
