# Generated by Django 3.2.3 on 2021-09-15 08:32
from functools import partial

from django.db import migrations

import easydmp.dmpt.models.questions.mixins
from easydmp.dmpt.utils import register_question_type


register_email_type = partial(register_question_type, 'iri')


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0003_emailquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRIQuestion',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=(easydmp.dmpt.models.questions.mixins.PrimitiveTypeMixin, easydmp.dmpt.models.questions.mixins.SaveMixin, 'dmpt.question'),
        ),
        migrations.RunPython(register_email_type, migrations.RunPython.noop),
    ]
