# Generated by Django 2.2.12 on 2020-05-27 12:30

from django.db import migrations, models
import easydmp.dmpt.models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0003_alter_section_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(easydmp.dmpt.models.NoCheckMixin, easydmp.dmpt.models.SimpleFramingTextMixin, 'dmpt.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('bool', 'bool'), ('choice', 'choice'), ('daterange', 'daterange'), ('multichoiceonetext', 'multichoiceonetext'), ('reason', 'reason'), ('shortfreetext', 'shortfreetext'), ('positiveinteger', 'positiveinteger'), ('date', 'date'), ('externalchoice', 'externalchoice'), ('extchoicenotlisted', 'extchoicenotlisted'), ('externalmultichoiceonetext', 'externalmultichoiceonetext'), ('extmultichoicenotlistedonetext', 'extmultichoicenotlistedonetext'), ('namedurl', 'namedurl'), ('multinamedurlonetext', 'multinamedurlonetext'), ('multidmptypedreasononetext', 'multidmptypedreasononetext')], max_length=32),
        ),
    ]
