# Generated by Django 2.2.18 on 2021-03-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0004_add_locked_to_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateimportmetadata',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='dmpt.TemplateImportMetadata'),
        ),
        migrations.AddField(
            model_name='templateimportmetadata',
            name='cloned_when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveConstraint(
            model_name='templateimportmetadata',
            name='tim_unique_template_per_origin_constraint',
        ),
    ]
