# Generated by Django 3.1.3 on 2021-05-05 11:20

from django.db import migrations, models


from easydmp.dmpt.utils import SectionPositionUtils


def reorder_sections(apps, schema_editor):
    ordered_template_sections = SectionPositionUtils.ordered_template_sections
    set_order = SectionPositionUtils.set_order
    Template = apps.get_model('dmpt', 'Template')
    for template in Template.objects.all():
        new_order = [obj.pk for obj in ordered_template_sections(template)]
        set_order(template.sections.all(), new_order)


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0005_clonable_TemplateImportMetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='position',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='A specific position may only occur once per template'),
        ),
        migrations.RunPython(reorder_sections, migrations.RunPython.noop),
    ]
