# Generated by Django 3.2.3 on 2021-11-04 10:33

from django.db import migrations, models


BRANCHING_POSSIBLE_FIELDS = [
    'bool',
    'choice',
    'extchoicenotlisted',
    'extmultichoicenotlistedonetext',
]


def set_branching_possible(apps, schema_editor):
    QuestionType = apps.get_model('dmpt', 'QuestionType')
    QuestionType.objects.filter(
        id__in=BRANCHING_POSSIBLE_FIELDS
    ).update(branching_possible=True)


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0005_question_has_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='branching_possible',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_branching_possible, migrations.RunPython.noop),
    ]
