# Generated by Django 2.2.12 on 2020-07-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0005_noop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cannedanswer',
            name='edge',
        ),
        migrations.RemoveField(
            model_name='question',
            name='node',
        ),
    ]
