# Generated by Django 3.1.3 on 2021-05-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0006_uneditable_section_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('template', 'title'), name='dmpt_section_unique_title_per_template'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('template', 'position'), name='dmpt_section_unique_position_per_template'),
        ),
    ]
