# Generated by Django 2.2.12 on 2020-07-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0006_remove_old_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='reveal_questions',
            field=models.BooleanField(default=False, help_text='Should the questions be shown in the generated text?'),
        ),
    ]
