# Generated by Django 3.2.12 on 2022-03-17 08:21

from django.db import migrations, models
import easydmp.dmpt.models.questions.mixins


def set_can_identify(apps, schema_editor):
    QuestionType = apps.get_model('dmpt', 'QuestionType')
    QuestionType.objects.get_or_create(id='typedidentifier', can_identify=True)
    sft = QuestionType.objects.get(id='shortfreetext')
    sft.can_identify = True
    sft.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0006_questiontype_branching_possible'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='can_identify',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_can_identify, migrations.RunPython.noop),
    ]
