# Generated by Django 3.2.3 on 2021-07-08 07:40

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0007_fix_uniqueness_contraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateimportmetadata',
            name='mappings',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
