# Generated by Django 3.2.12 on 2022-03-17 08:29

from django.db import migrations
import easydmp.dmpt.models.questions.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0007_add_can_identify_to_QuestionType'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypedIdentifierQuestion',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=(easydmp.dmpt.models.questions.mixins.SaveMixin, 'dmpt.question'),
        ),
    ]
