# Generated by Django 2.2.12 on 2020-08-31 11:34

from django.db import migrations
import easydmp.dmpt.models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0008_noop_add_input_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageForecastQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(easydmp.dmpt.models.NoCheckMixin, 'dmpt.question'),
        ),
    ]
