# Generated by Django 3.2.12 on 2022-03-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0008_typedidentifierquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='identifier_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmpt.question'),
        ),
    ]
