# Generated by Django 3.2.12 on 2022-05-11 06:14

from django.db import migrations
import easydmp.dmpt.models.questions.mixins


def register_trilean_type(apps, _):
    QuestionType = apps.get_model('dmpt', 'QuestionType')
    QuestionType.objects.create(id='trilean', branching_possible=True)


def unregister_trilean_type(apps, _):
    QuestionType = apps.get_model('dmpt', 'QuestionType')
    try:
        qt = QuestionType.objects.get(id='trilean')
    except QuestionType.DoesNotExist:
        pass
    else:
        qt.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0009_section_identifier_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrileanQuestion',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=(easydmp.dmpt.models.questions.mixins.ChoiceValidationMixin, easydmp.dmpt.models.questions.mixins.SaveMixin, 'dmpt.question'),
        ),
        migrations.RunPython(register_trilean_type, unregister_trilean_type),
    ]
