# Generated by Django 2.2.11 on 2020-09-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0009_storageforecastquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='optional',
            field=models.BooleanField(default=False, help_text='True if this section is optional. The template designer needs to provide a wording to an automatically generated question at the start of the section.'),
        ),
    ]
