# Generated by Django 3.2.12 on 2022-05-23 06:47

from django.db import migrations
import easydmp.dmpt.models.questions.mixins


def register_datetime_type(apps, _):
    QuestionType = apps.get_model('dmpt', 'QuestionType')
    QuestionType.objects.create(id='datetime')


def unregister_datetime_type(apps, _):
    QuestionType = apps.get_model('dmpt', 'QuestionType')
    try:
        qt = QuestionType.objects.get(id='datetime')
    except QuestionType.DoesNotExist:
        pass
    else:
        qt.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0010_trileanquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeQuestion',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=(easydmp.dmpt.models.questions.mixins.PrimitiveTypeMixin, easydmp.dmpt.models.questions.mixins.SaveMixin, 'dmpt.question'),
        ),
        migrations.RunPython(register_datetime_type, unregister_datetime_type),
    ]
