# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0010_add_multinamedurlonetextquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalChoiceNotListedQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('dmpt.question',),
        ),
        migrations.CreateModel(
            name='ExternalMultipleChoiceNotListedOneTextQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('dmpt.question',),
        ),
        migrations.CreateModel(
            name='MultiDMPTypedReasonOneTextQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('dmpt.question',),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('bool', 'bool'), ('choice', 'choice'), ('daterange', 'daterange'), ('multichoiceonetext', 'multichoiceonetext'), ('reason', 'reason'), ('positiveinteger', 'positiveinteger'), ('externalchoice', 'externalchoice'), ('extchoicenotlisted', 'extchoicenotlisted'), ('externalmultichoiceonetext', 'externalmultichoiceonetext'), ('extmultichoicenotlistedonetext', 'extmultichoicenotlistedonetext'), ('namedurl', 'namedurl'), ('multinamedurlonetext', 'multinamedurlonetext'), ('multidmptypedreasononetext', 'multidmptypedreasononetext')], max_length=32),
        ),
    ]
