# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0011_auto_20180111_0955'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['input_type', 'id'], name='dmpt_questi_input_t_d0047e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['section', 'position'], name='dmpt_questi_section_9fdc5f_idx'),
        ),
    ]
