# Generated by Django 2.2.16 on 2020-11-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0011_section_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='repeatable',
            field=models.BooleanField(default=False, help_text='True if this section is repeatable. This means a plan can have multiple answersets for this section.'),
        ),
    ]
