# Generated by Django 3.2.12 on 2022-06-13 12:12

from django.db import migrations
import easydmp.dmpt.models.questions.mixins


def register_multistring_type(apps, _):
    QuestionType = apps.get_model('dmpt', 'QuestionType')
    QuestionType.objects.create(id='multistring')


def unregister_multistring_type(apps, _):
    QuestionType = apps.get_model('dmpt', 'QuestionType')
    try:
        qt = QuestionType.objects.get(id='multistring')
    except QuestionType.DoesNotExist:
        pass
    else:
        qt.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0011_multistringquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultistringQuestion',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=(easydmp.dmpt.models.questions.mixins.NoCheckMixin, easydmp.dmpt.models.questions.mixins.SaveMixin, 'dmpt.question'),
        ),
        migrations.RunPython(register_multistring_type, unregister_multistring_type),
    ]
