# Generated by Django 3.2.12 on 2022-07-04 07:12

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    Template = apps.get_model('dmpt', 'Template')
    for row in Template.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0012_multistringquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='uuid',
            field=models.UUIDField(editable=False, help_text='Created on first save', null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='template',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Created on first save', unique=True),
        ),
    ]
