# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0012_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cannedanswer',
            name='edge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payload', to='flow.Edge'),
        ),
        migrations.AlterField(
            model_name='question',
            name='node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payload', to='flow.Node'),
        ),
    ]
