# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0013_decouple_from_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cannedanswer',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Position in question. Just used for ordering.', null=True),
        ),
    ]
