# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0014_cannedanswer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='label',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='section',
            name='section_depth',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='section',
            name='super_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='dmpt.Section'),
        ),
    ]
