# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0015_add_subsection_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='obligatory',
            field=models.NullBooleanField(),
        ),
    ]
