# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0019_migrate_to_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='obligatory',
            field=models.NullBooleanField(default=True),
        ),
    ]
