# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0021_section_branching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='obligatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='branching',
            field=models.BooleanField(default=False),
        ),
    ]
