# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0022_set_not_null'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cannedanswer',
            index=models.Index(fields=['question', 'position'], name='dmpt_preferred_ca_ordering_idx'),
        ),
        migrations.AddIndex(
            model_name='cannedanswer',
            index=models.Index(fields=['question', 'position', 'id'], name='dmpt_fallback_ca_ordering_idx'),
        ),
    ]
