# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0023_add_ordering_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='domain_specific',
            field=models.BooleanField(default=False),
        ),
    ]
