# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0025_add_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='optional_canned_text',
            field=models.TextField(blank=True),
        ),
    ]
