# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-08 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0029_remove_TemplateAccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='template',
            name='more_info',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='retired',
            field=models.DateTimeField(blank=True, help_text='Date after which the template should no longer be used.', null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='published',
            field=models.DateTimeField(blank=True, help_text='Date when the template is publically available, and set read-only.', null=True),
        ),
    ]
