# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-24 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0030_more_template_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cannedanswer',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='dmpt.CannedAnswer'),
        ),
        migrations.AddField(
            model_name='cannedanswer',
            name='cloned_when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='dmpt.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='cloned_when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='dmpt.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='cloned_when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='dmpt.Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='cloned_when',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
