# Generated by Django 3.2.17 on 2020-11-24 13:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmpt', '0001_squashed_0011_section_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This title will be used as the title of the generated\n        data management plan document. We recommend something that includes the\n        name of the project the plan is for, e.g., "Preliminary data plan for\n        &lt;project&gt;", "Revised data plan for &lt;project&gt;", etc.', max_length=255)),
                ('abbreviation', models.CharField(blank=True, help_text='A short abbreviation of the plan title, for internal use. Not shown in the generated file.', max_length=8)),
                ('version', models.PositiveIntegerField(default=1)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('previous_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_plans', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_plans', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='dmpt.Template')),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_plans', to=settings.AUTH_USER_MODEL)),
                ('locked', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_plans', to=settings.AUTH_USER_MODEL)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('generated_html', models.TextField(blank=True)),
                ('doi', models.URLField(blank=True, default='', help_text='Use the URLified DOI, https://dx.doi.org/<doi>')),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('valid', models.BooleanField(blank=True, null=True)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='plan.Plan')),
                ('cloned_when', models.DateTimeField(blank=True, null=True)),
                ('visited_sections', models.ManyToManyField(blank=True, related_name='_plan_visited_sections_+', to='dmpt.Section')),
                ('search_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField()),
                ('last_validated', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='plan.Plan')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmpt.Section')),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='plan.AnswerSet')),
                ('cloned_when', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('plan', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField()),
                ('last_validated', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_validity', to='plan.Plan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmpt.Question')),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='plan.Answer')),
                ('cloned_when', models.DateTimeField(blank=True, null=True)),
                ('answerset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='plan.AnswerSet')),
            ],
            options={
                'unique_together': {('plan', 'question')},
            },
        ),
        migrations.CreateModel(
            name='PlanAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloned_when', models.DateTimeField(blank=True, null=True)),
                ('may_edit', models.BooleanField(blank=True, null=True)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='plan.PlanAccess')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='plan.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'plan')},
            },
        ),
    ]
