# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmpt', '0003_auto_20170921_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=8)),
                ('version', models.PositiveIntegerField(default=1)),
                ('data', jsonfield.fields.JSONField(default={})),
                ('previous_data', jsonfield.fields.JSONField(default={})),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_plans', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_plans', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='dmpt.Template')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set([('version', 'title')]),
        ),
    ]
