# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-04 06:50
from __future__ import unicode_literals

from copy import deepcopy

from django.db import migrations

from easydmp.lib.convert.answers import bool_to_yesno, convert_plan_answers


def convert_boolean_answers(apps, schema_editor):
    Question = apps.get_model('dmpt', 'Question')
    question_ids = (Question.objects
                    .filter(input_type='bool')
                    .values_list('id', flat=True))
    Plan = apps.get_model('plan', 'Plan')
    convert_plan_answers(bool_to_yesno, question_ids, Plan.objects.all())


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_squashed_0024_cleanup_plan_editor_groups'),
        ('dmpt', '0001_squashed_0031_improve_cloning'),
    ]

    operations = [
        migrations.RunPython(
            convert_boolean_answers,
            migrations.RunPython.noop
        ),
    ]
