# Generated by Django 3.2.3 on 2021-11-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_squashed_0005_auto_20201016_1539_squashed_0019_link_answerset_with_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='skipped',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
