# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0004_auto_20170922_0911'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set([('template', 'version', 'title')]),
        ),
    ]
