# Generated by Django 3.2.3 on 2021-11-25 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_answerset_skipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanImportMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloned_when', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(help_text='Where the plan was imported from', max_length=255)),
                ('original_template_pk', models.IntegerField(help_text="Copy of the original plan's template's primary key")),
                ('original_plan_pk', models.IntegerField(help_text="Copy of the original plan's primary key")),
                ('originally_cloned_from', models.IntegerField(blank=True, help_text='Copy of the original plan\'s "cloned_from"', null=True)),
                ('originally_locked', models.DateTimeField(blank=True, help_text='Copy of the original plan\'s "locked"', null=True)),
                ('originally_published', models.DateTimeField(blank=True, help_text='Copy of the original plan\'s "published"', null=True)),
                ('variant', models.CharField(default='single version', max_length=32)),
                ('imported', models.DateTimeField(default=django.utils.timezone.now)),
                ('imported_via', models.CharField(default='CLI', max_length=255)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='plan.planimportmetadata')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_metadata', to='plan.plan')),
            ],
            options={
                'verbose_name_plural': 'plan import metadata',
            },
        ),
        migrations.AddIndex(
            model_name='planimportmetadata',
            index=models.Index(fields=['original_plan_pk'], name='pim_lookup_original_idx'),
        ),
    ]
