# Generated by Django 2.2.16 on 2020-10-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_change_booleanquestion_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='search_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
