# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('plan', '0002_auto_20170926_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='editor_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.Group'),
        ),
    ]
