# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 07:09
from __future__ import unicode_literals

from django.db import migrations


def set_editor_group(apps, schema_editor):
    Plan = apps.get_model('plan', 'Plan')
    Group = apps.get_model('auth', 'Group')
    for plan in Plan.objects.all():
        group, _ = Group.objects.get_or_create(name='plan-editors-{}'.format(plan.pk))
        plan.editor_group = group
        plan.save()
        plan.added_by.groups.add(plan.editor_group)


def unset_editor_group(apps, schema_editor):
    Plan = apps.get_model('plan', 'Plan')
    for plan in Plan.objects.all():
        group = plan.editor_group
        plan.editor_group = None
        plan.save()
        group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_plan_editor_group'),
    ]

    operations = [
        migrations.RunPython(set_editor_group, unset_editor_group),
    ]
