# Generated by Django 3.2.12 on 2022-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_add_planimportmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='identifier',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
