# Generated by Django 2.2.16 on 2020-10-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20201016_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answerset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='plan.AnswerSet'),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='plan.Plan'),
        ),
    ]
