# Generated by Django 3.2.12 on 2022-09-27 09:41

from django.db import migrations, models


def ensure_skipped_is_never_false(apps, _):
    AnswerSet = apps.get_model('plan', 'AnswerSet')
    AnswerSet.objects.filter(skipped=False).update(skipped=None)


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_answerset_identifier'),
    ]

    operations = [
        migrations.RunPython(ensure_skipped_is_never_false, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='answerset',
            name='skipped',
            field=models.BooleanField(blank=True, help_text='True or None', null=True),
        ),
        migrations.AddConstraint(
            model_name='answerset',
            constraint=models.CheckConstraint(check=models.Q(('skipped', True)), name='plan_answerset_skipped_never_false'),
        ),
    ]
