# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_set_editor_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set([]),
        ),
    ]
