# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0015_add_subsection_support'),
        ('plan', '0005_no_sqlunique_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='visited_sections',
            field=models.ManyToManyField(related_name='_plan_visited_sections_+', to='dmpt.Section'),
        ),
    ]
