# Generated by Django 2.2.16 on 2020-11-04 08:45

from django.db import migrations


def link_answer(apps, schema_editor):
    """
    Ensures all answers have an AnswerSet
    """
    Answer = apps.get_model('plan', 'Answer')
    AnswerSet = apps.get_model('plan', 'AnswerSet')
    for answer in Answer.objects.all():
        answer.answerset = AnswerSet.objects.get(plan=answer.plan)
        answer.save()


def unlink_answer(apps, schema_editor):
    Answer = apps.get_model('plan', 'Answer')
    for answer in Answer.objects.all():
        answer.answerset = None
        answer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20201016_1539'),
    ]

    operations = [
        migrations.RunPython(link_answer, reverse_code=unlink_answer),
    ]
