# Generated by Django 2.2.17 on 2020-11-24 14:00

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# easydmp.plan.migrations.0008_convert_to_jsonb

class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_squashed_0005_auto_20201016_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersets', to='plan.Plan'),
        ),
    ]
