# Generated by Django 2.2.16 on 2020-11-11 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_link_answer_to_answerset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersets', to='plan.Plan'),
        ),
    ]
