# Generated by Django 2.2.13 on 2020-12-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0002_section_repeatable'),
        ('plan', '0007_auto_20201111_1411_squashed_0010_delete_plancomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersets', to='dmpt.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('plan', 'question', 'answerset')},
        ),
        migrations.AlterUniqueTogether(
            name='answerset',
            unique_together=set(),
        ),
    ]
