# Generated by Django 2.2.13 on 2020-12-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_auto_20201215_0851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerset',
            unique_together=set(),
        ),
    ]
