# Generated by Django 2.2.13 on 2021-02-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0003_TemplateImportMetadata'),
        ('plan', '0008_answerset_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersets', to='dmpt.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('plan', 'question', 'answerset')},
        ),
        migrations.AlterUniqueTogether(
            name='answerset',
            unique_together=set(),
        ),
    ]
