# Generated by Django 2.2.13 on 2020-12-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0002_section_repeatable'),
        ('plan', '0009_auto_20201215_1024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('plan', 'question', 'answerset')},
        ),
    ]
