# Generated by Django 3.2.3 on 2021-07-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0008_switch_to_native_JSONField'),
        ('plan', '0010_switch_to_native_JSONField'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='plan.plan'),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersets', to='dmpt.section'),
        ),
    ]
