# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 09:14
from uuid import uuid4

from django.db import migrations


def generate_uuids(apps, schema_editor):
    Plan = apps.get_model('plan', 'Plan')
    for plan in Plan.objects.filter(uuid__isnull=True):
        plan.uuid = uuid4()
        plan.save()


def unset_uuids(apps, schema_editor):
    Plan = apps.get_model('plan', 'Plan')
    for plan in Plan.objects.all():
        plan.uuid = None
        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_add_locking_fields'),
    ]

    operations = [
        migrations.RunPython(generate_uuids, unset_uuids),
    ]
