# Generated by Django 3.2.3 on 2021-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='identifier',
            field=models.CharField(blank=True, default='1', max_length=120),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='answerset',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='answerset',
            constraint=models.UniqueConstraint(fields=('plan', 'section', 'identifier'), name='plan_answerset_unique_identifiers'),
        ),
    ]
