# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 06:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmpt', '0016_question_obligatory'),
        ('plan', '0011_generate_uuids'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_comments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plan.Plan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmpt.Question')),
            ],
        ),
    ]
