# Generated by Django 3.2.3 on 2021-07-08 12:14

from django.db import migrations


def link_answerset(apps, schema_editor):
    Answer = apps.get_model('plan', 'Answer')
    AnswerSet = apps.get_model('plan', 'AnswerSet')
    answers_to_fix = Answer.objects.select_related('question').filter(answerset__isnull=True)
    for answer in answers_to_fix:
        plan_id = answer.plan_id
        section_id = answer.question.section_id
        answerset = AnswerSet.objects.get(plan_id=plan_id, section_id=section_id)
        answer.answerset = answerset
    Answer.objects.bulk_update(answers_to_fix, ['answerset'], batch_size=1000)


def unlink_answerset(apps, schema_editor):
    Answer = apps.get_model('plan', 'Answer')
    answers_to_fix = Answer.objects.filter(answerset__isnull=False)
    answers_to_fix.update(answerset=None)


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_add_identifier_to_answerset'),
    ]

    operations = [
        migrations.RunPython(link_answerset, unlink_answerset)
    ]
