# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_plan_generated_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='doi',
            field=models.URLField(blank=True, default='', help_text='Use the URLified DOI, https://dx.doi.org/<doi>'),
        ),
    ]
