# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easydmp_project', '0001_initial'),
        ('plan', '0015_update_helptexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easydmp_project.Project'),
        ),
    ]
