# Generated by Django 3.2.3 on 2021-07-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_noop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answerset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='plan.answerset'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('answerset', 'question'), name='plan_answer_one_answer_per_question'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='plan',
        ),
    ]
