# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0016_question_obligatory'),
        ('plan', '0015_update_helptexts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(help_text='This title will be used as the title of the generated\n        data management plan document. We recommend something that includes the\n        name of the project the plan is for, e.g., "Preliminary data plan for\n        &lt;project&gt;", "Revised data plan for &lt;project&gt;", etc.', max_length=255),
        ),
    ]
