# Generated by Django 3.2.3 on 2021-07-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_drop_Answer_plan_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='data',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='previous_data',
        ),
    ]
