# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmpt', '0016_question_obligatory'),
        ('plan', '0016_alter_title_nosql'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionValidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField()),
                ('last_validated', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='plan.Plan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmpt.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SectionValidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField()),
                ('last_validated', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='plan.Plan')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmpt.Section')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='question_validity',
            field=models.ManyToManyField(through='plan.QuestionValidity', to='dmpt.Question'),
        ),
        migrations.AddField(
            model_name='plan',
            name='section_validity',
            field=models.ManyToManyField(through='plan.SectionValidity', to='dmpt.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionvalidity',
            unique_together=set([('plan', 'section')]),
        ),
        migrations.AlterUniqueTogether(
            name='questionvalidity',
            unique_together=set([('plan', 'question')]),
        ),
    ]
