# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0017_add_validation_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='question_validity',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='section_validity',
        ),
        migrations.AlterField(
            model_name='questionvalidity',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_validity', to='plan.Plan'),
        ),
        migrations.AlterField(
            model_name='sectionvalidity',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_validity', to='plan.Plan'),
        ),
    ]
