# Generated by Django 3.2.3 on 2021-07-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0017_drop_data_from_Plan'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answerset',
            name='plan_answerset_unique_identifiers',
        ),
        migrations.AddField(
            model_name='answerset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answersets', to='plan.answerset'),
        ),
        migrations.AddConstraint(
            model_name='answerset',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('plan', 'section', 'identifier'), name='plan_answerset_unique_identifiers'),
        ),
        migrations.AddConstraint(
            model_name='answerset',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('plan', 'section', 'parent', 'identifier'), name='plan_answerset_unique_identifiers_parent'),
        ),
    ]
