# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_validity_as_fk_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='valid',
            field=models.NullBooleanField(),
        ),
    ]
