# Generated by Django 3.2.3 on 2021-07-22 14:03

from django.db import migrations


def add_parents(apps, schema_editor):
    AnswerSet = apps.get_model('plan', 'AnswerSet')
    Plan = apps.get_model('plan', 'Plan')
    Section = apps.get_model('dmpt', 'Section')
    # repair (add missing answersets)
    for template_id, super_section_id in Section.objects.filter(super_section__isnull=False).values_list('template', 'super_section').order_by('template_id'):
        for plan_id in Plan.objects.filter(template_id=template_id).values_list('id', flat=True):
            try:
                AnswerSet.objects.get_or_create(plan_id=plan_id, section_id=super_section_id)
            except AnswerSet.MultipleObjectsReturned:
                pass
    # set parents
    for answerset in AnswerSet.objects.filter(parent__isnull=True).select_related('section__super_section'):
        super_section = answerset.section.super_section
        if not super_section:
            continue
        parent_answerset = AnswerSet.objects.filter(
            section=super_section,
            plan=answerset.plan,
        ).order_by('pk').first()
        if parent_answerset:
            answerset.parent = parent_answerset
            answerset.save()


def remove_parents(apps, schema_editor):
    AnswerSet = apps.get_model('plan', 'AnswerSet')
    AnswerSet.objects.update(parent=None)


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_answerset_parent'),
        ('dmpt', '0008_switch_to_native_JSONField'),
    ]

    operations = [
        migrations.RunPython(add_parents, remove_parents),
    ]
