# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-28 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_add_validation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='plan.Plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='cloned_when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionvalidity',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='plan.QuestionValidity'),
        ),
        migrations.AddField(
            model_name='questionvalidity',
            name='cloned_when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionvalidity',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='plan.SectionValidity'),
        ),
        migrations.AddField(
            model_name='sectionvalidity',
            name='cloned_when',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
