# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 07:05
from __future__ import unicode_literals

from django.db import migrations

from easydmp.plan.utils import create_plan_editor_group


def copy_editors_to_planaccess(apps, schema_editor):
    Plan = apps.get_model('plan', 'Plan')
    PlanAccess = apps.get_model('plan', 'PlanAccess')
    for plan in Plan.objects.exclude(editor_group__isnull=True):
        editors = plan.editor_group.user_set.all()
        for editor in editors:
            pa, _ = PlanAccess.objects.update_or_create(
                plan=plan,
                user=editor,
                defaults={'may_edit': True}
            )


def copy_planaccess_editors_to_editor_group(apps, schema_editor):
    Plan = apps.get_model('plan', 'Plan')
    PlanAccess = apps.get_model('plan', 'PlanAccess')
    for pa in PlanAccess.objects.filter(may_edit=True):
        plan = pa.plan
        user = pa.user
        if not getattr(plan, 'editor_group', None):
            create_plan_editor_group(plan)
            plan.editor.group.add(user)



class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0021_planaccess'),
    ]

    operations = [
        migrations.RunPython(copy_editors_to_planaccess, copy_planaccess_editors_to_editor_group)
    ]
