# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0022_copy_editors_to_planaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='editor_group',
        ),
    ]
