# Generated by Django 3.2.3 on 2021-08-03 09:16

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('eventlog', '0001_squashed_0002_convert_to_jsonb'), ('eventlog', '0002_switch_to_native_JSONField')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actor', to='contenttypes.contenttype')),
                ('actor_object_id', models.TextField(db_index=True)),
                ('verb', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target', to='contenttypes.contenttype')),
                ('target_object_id', models.TextField(blank=True, db_index=True, null=True)),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_object', to='contenttypes.contenttype')),
                ('action_object_object_id', models.TextField(blank=True, db_index=True, null=True)),
                ('data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
