# Generated by Django 2.2.12 on 2020-10-23 09:30

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations

import json


def convert_to_jsonblob(apps, schema_editor):
    EventLog = apps.get_model('eventlog', 'EventLog')
    for ec in EventLog.objects.all():
        if isinstance(ec.data, str):
            ec.data = json.loads(ec.data)
            ec.save()


def convert_to_text(apps, schema_editor):
    "Will be converted back by previous migration in operations list"
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.RunPython(
            code=convert_to_jsonblob,
            reverse_code=convert_to_text,
        )
    ]
