# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='The name of the project a plan is for', max_length=255)),
                ('url', models.URLField(blank=True, default='', help_text='URL pointing to more information about the project, e.g., a home page')),
            ],
        ),
    ]
