# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmpt', '0001_squashed_0031_improve_cloning'),
    ]

    operations = [
        migrations.CreateModel(
            name='EEStoreCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eestore_pid', models.CharField(max_length=255, unique=True)),
                ('eestore_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('uri', models.URLField(blank=True)),
                ('pid', models.CharField(blank=True, max_length=255)),
                ('remote_id', models.CharField(max_length=255)),
                ('data', jsonfield.fields.JSONField(default={})),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'easydmp_eestore_cache',
                'verbose_name': 'eestore cache',
            },
        ),
        migrations.CreateModel(
            name='EEStoreMount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'easydmp_eestore_mount',
                'verbose_name': 'eestore mount',
            },
        ),
        migrations.CreateModel(
            name='EEStoreSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'easydmp_eestore_source',
                'verbose_name': 'eestore source',
            },
        ),
        migrations.CreateModel(
            name='EEStoreType',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'easydmp_eestore_type',
                'verbose_name': 'eestore type',
            },
        ),
        migrations.AddField(
            model_name='eestoresource',
            name='eestore_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='eestore.EEStoreType'),
        ),
        migrations.AddField(
            model_name='eestoremount',
            name='eestore_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eestore.EEStoreType'),
        ),
        migrations.AddField(
            model_name='eestoremount',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eestore', to='dmpt.Question'),
        ),
        migrations.AddField(
            model_name='eestoremount',
            name='sources',
            field=models.ManyToManyField(to='eestore.EEStoreSource'),
        ),
        migrations.AddField(
            model_name='eestorecache',
            name='eestore_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='eestore.EEStoreType'),
        ),
        migrations.AddField(
            model_name='eestorecache',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='eestore.EEStoreSource'),
        ),
    ]
