# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eestorecache',
            options={'verbose_name': 'EEStore cache'},
        ),
        migrations.AlterModelOptions(
            name='eestoremount',
            options={'verbose_name': 'EEStore mount'},
        ),
        migrations.AlterModelOptions(
            name='eestoresource',
            options={'verbose_name': 'EEStore source'},
        ),
        migrations.AlterModelOptions(
            name='eestoretype',
            options={'verbose_name': 'EEStore type'},
        ),
        migrations.AlterField(
            model_name='eestoremount',
            name='sources',
            field=models.ManyToManyField(blank=True, help_text="Select a subset of the eestore types' sources here. Keep empty to select all types.", to='eestore.EEStoreSource'),
        ),
    ]
