# Generated by Django 3.2.3 on 2021-07-08 07:40

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eestore', '0001_squashed_0002_convert_to_jsonb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eestorecache',
            name='data',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
