# Generated by Django 2.2.12 on 2020-10-16 10:27

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations

import json


def convert_to_jsonblob(apps, schema_editor):
    EEStoreCache = apps.get_model('eestore', 'EEStoreCache')
    for ec in EEStoreCache.objects.all():
        if isinstance(ec.data, str):
            ec.data = json.loads(ec.data)
            ec.save()


def convert_to_text(apps, schema_editor):
    "Will be converted back by previous migration in operations list"
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('eestore', '0001_squashed_0002_update_django_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eestorecache',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.RunPython(
            code=convert_to_jsonblob,
            reverse_code=convert_to_text,
        )
    ]
