# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eestore', '0002_update_django_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='eestoretype',
            name='endpoint',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='eestoretype',
            unique_together=set([('name', 'endpoint')]),
        ),
        migrations.AddField(
            model_name='eestoresource',
            name='endpoint',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='eestoresource',
            unique_together=set([('eestore_type', 'name')]),
        ),
    ]
