# Generated by Django 2.2.13 on 2021-02-08 12:53

from django.db import migrations
import easydmp.auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('easydmp_auth', '0001_squashed_0003_upstream_change'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', easydmp.auth.models.UserManager()),
            ],
        ),
    ]
