# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-01 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0001_squashed_0005_auto_20201016_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanInvitation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('used', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plan')),
                ('type', models.CharField(choices=[('edit', 'Edit'), ('view', 'View')], default='view', max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanEditorInvitation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('invitation.planinvitation',),
        ),
        migrations.CreateModel(
            name='PlanViewerInvitation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('invitation.planinvitation',),
        ),
    ]
