# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeditorinvitation',
            name='type',
            field=models.CharField(choices=[('edit', 'Edit'), ('view', 'View')], default='edit', max_length=4),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='PlanEditorInvitation',
            new_name='PlanInvitation',
        ),
        migrations.CreateModel(
            name='PlanEditorInvitation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('invitation.planinvitation',),
        ),
        migrations.CreateModel(
            name='PlanViewerInvitation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('invitation.planinvitation',),
        ),
    ]
