# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-04 07:15
from __future__ import unicode_literals

from django.db import migrations


def print_edge(edge, prefix):
    print('{} edge: Node: {}, next: {}, condition: {}'.format(
        prefix,
        edge.prev_node.id if edge.prev_node else None,
        edge.next_node.id if edge.next_node else None,
        edge.condition,
    ))


def convert_question_truefalse_edge_to_yesno_edge(apps, schema_editor):
    Question = apps.get_model('dmpt', 'Question')
    node_ids = (Question.objects
                .filter(input_type='bool')
                .values_list('node__id', flat=True))
    Edge = apps.get_model('flow', 'Edge')
    for edge in (Edge.objects
                 .filter(condition__in=('True', 'False'),
                         prev_node__id__in=node_ids)):
        print_edge(edge, 'Old')
        change = False
        if edge.condition == 'True':
            edge.condition = 'Yes'
            change = True
        elif edge.condition == 'False':
            edge.condition = 'No'
            change = True
        if change:
            edge.save()
        print_edge(edge, 'New')


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_squashed_0006_add_clonable_model_fields'),
        ('dmpt', '0001_squashed_0031_improve_cloning'),
        ('plan', '0002_change_booleanquestion_answers'),
    ]

    operations = [
        migrations.RunPython(
            convert_question_truefalse_edge_to_yesno_edge,
            migrations.RunPython.noop
        ),
    ]
