# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
