# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_node_end'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together=set([('condition', 'prev_node', 'next_node')]),
        ),
    ]
