# Generated by Django 2.2.12 on 2020-07-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_squashed_0006_add_clonable_model_fields'),
        ('dmpt', '0006_remove_old_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsa',
            name='cloned_from',
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='node',
            name='cloned_from',
        ),
        migrations.RemoveField(
            model_name='node',
            name='depends',
        ),
        migrations.RemoveField(
            model_name='node',
            name='fsa',
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='FSA',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
