# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_alter_edge_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsa',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterField(
            model_name='node',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
    ]
