# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_lengthen_slug_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsa',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
