# Generated by Django 3.2.12 on 2022-05-05 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmpt', '0012_multistringquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDADCSKey',
            fields=[
                ('slug', models.SlugField(max_length=60, primary_key=True, serialize=False)),
                ('path', models.CharField(help_text='Path to value in jq path-syntax', max_length=60, unique=True)),
                ('repeatable', models.BooleanField(blank=True, default=False)),
                ('optional', models.BooleanField(blank=True, default=False)),
                ('input_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dmpt.questiontype')),
            ],
        ),
        migrations.CreateModel(
            name='RDADCSSectionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdadcs.rdadcskey')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dmpt.section')),
            ],
            options={
                'unique_together': {('key', 'section')},
            },
        ),
        migrations.CreateModel(
            name='RDADCSQuestionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdadcs.rdadcskey')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dmpt.question')),
            ],
            options={
                'unique_together': {('key', 'question')},
            },
        ),
    ]
