# Generated by Django 3.2.12 on 2022-05-24 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_answerset_identifier'),
        ('rdadcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDADCSImportMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.TextField()),
                ('original_id_type', models.CharField(choices=[('handle', 'handle'), ('doi', 'doi'), ('ark', 'ark'), ('url', 'url'), ('other', 'other')], max_length=6)),
                ('originally_created', models.DateTimeField(help_text='Copy of the original plan\'s "created"')),
                ('originally_modified', models.DateTimeField(help_text='Copy of the original plan\'s "modified"')),
                ('original_json', models.JSONField()),
                ('imported', models.DateTimeField(default=django.utils.timezone.now)),
                ('imported_via', models.CharField(default='CLI', max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_rdadcs_metadata', to='plan.plan')),
            ],
            options={
                'verbose_name_plural': 'rdadcs plan import metadata',
            },
        ),
    ]
