name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set Environment Variables
      run: |
          echo "POSTGRES_DB=easydmp_db" >> $GITHUB_ENV
          echo "POSTGRES_USER=easydmp" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=cdfgh6rt578gtvfhyj" >> $GITHUB_ENV

    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
          postgresql db: $POSTGRES_DB
          postgresql user: $POSTGRES_USER
          postgresql password: $POSTGRES_PASSWORD

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip "setuptools<46" wheel
        pip install tox tox-gh-actions

    - name: Lint with flake8
      run: |
        tox -e flake8

    - name: Test with tox
      env:
        POSTGRES: true
        DMP_DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost/$POSTGRES_DB
      run: |
        tox
